### ISSUE TITLE
[BUG] Data cell count does not match table header column count

### ISSUE THREAD

**Issue by cloudworxx** [Protoqol/Prequel#44] opened 2019-07-15 11:13 UTC
For the default users table in Laravel, the cell count of table data does not match header cell count. 

**To Reproduce**
1. create a blank Laravel installation
2. run artisan make:auth
3. Register default user
4. Install Prequel
5. Open users table

The header has the following fields:
id, name, email, email_verified_at, password, remember_token, created_at, updated_at

The data row only has 
id, name, email, email_verified_at, created_at, updated_at

**Screenshots**
![grafik](https://user-images.githubusercontent.com/174149/61212341-44f21600-a702-11e9-9c95-349fc7df541d.png)

**Comment by QuintenJustus** [comment] 2019-07-15 11:42
Looks like duplicate of #37.

**Comment by QuintenJustus** [comment] 2019-07-15 21:33
This has been fixed, closing now.

**Closed by QuintenJustus** 2019-07-15 21:33 UTC
