### ISSUE TITLE
[BUG] Can't make it work with Homestead

### ISSUE THREAD

**Issue by godhandkiller** [Protoqol/Prequel#14] opened 2019-07-08 16:46 UTC
So I wanted to try this package, I installed on my project but I have this error message when I want go to /prequel

![prequel1](https://user-images.githubusercontent.com/18409311/60827398-56b94380-a16d-11e9-8286-851a0d800062.PNG)

This is the database connection on my .env file

`
DB_CONNECTION=mysql
`
`
DB_HOST=127.0.0.1
`
`
DB_PORT=33060
`
`
DB_DATABASE=prequel
`
`
DB_USERNAME=homestead
`
`
DB_PASSWORD=secret
`

**Comment by QuintenJustus** [comment] 2019-07-08 17:22
Hi, does the database work when not using prequel?

**Comment by igor-popovski** [comment] 2019-07-08 17:31
![image](https://user-images.githubusercontent.com/41303752/60830179-e9320500-a1b6-11e9-8191-c0ea37fdf6c2.png)

And i am getting this error even though i have configured the database correctly and i have the migrations done since i can access them in Navicat? What am i missing here?

**Comment by mchlbatista** [comment] 2019-07-08 17:36
Did you create a db named prequel? Is your MySQL instance using port 33060 and not 3306? Can you connect to you db using other program?

**Comment by godhandkiller** [comment] 2019-07-08 17:56
@QuintenJustus @mchlbatista 

I use DataGrip to manage my database and yes it's working in there, I have my database named prequel with all the migrations

**Comment by mchlbatista** [comment] 2019-07-08 20:51
I will give it a look.

**Comment by mchlbatista** [comment] 2019-07-08 21:15
Tested with your current configuration and it worked without problems. Notice that your current config is using a custom MySQL port "33060".

Configuration used

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=33060 // Please check that your config is using the right port (by default 3306)
DB_DATABASE=prequel
DB_USERNAME=homestead
DB_PASSWORD=secret
```

![Screenshot_2019-07-08_16-07](https://user-images.githubusercontent.com/20080764/60843095-4c15a300-a19b-11e9-9391-a09d12e825b0.png)

**Comment by QuintenJustus** [comment] 2019-07-08 22:18
Thanks for your help @mchlbatista! 

@godhandkiller did the config publish correctly (`config/prequel.php`)?

**Comment by godhandkiller** [comment] 2019-07-09 00:01
Thank you @mchlbatista for checking, unfortunately is not working for me still.

@QuintenJustus yes I saw the file and I even did just a dd() of the env variables and they are correct.
I found it weird that on the error message says 
`- You're using an irregular port number, usually the port is 3306 (Yours is: NaN)`
Implying that my port is empty, I thought it was something to do that my homestead uses the port 33060 but since @mchlbatista did a test and worked for him, I don't know what else to do.

**Comment by mchlbatista** [comment] 2019-07-09 00:06
Be sure that you ran

```
$ php artisan vendor:publish --tag=config
$ php artisan vendor:publish --tag=public
```
And try to run 

```
php artisan config:clear
```

The latest will clear the config cache

**Comment by James-N-M** [comment] 2019-07-09 00:56
I can confirm that it does work on laravel homestead. Double check your database is created and run the commands mentioned above.

**Comment by QuintenJustus** [comment] 2019-07-09 01:21
Thanks @mchlbatista & @James-N-M!

@igor-popovski your issue seems unrelated, could you open a separate issue for your issue? Thanks in advance!

@godhandkiller I’ll take a closer look at this issue, but for now the advice given above is the best there is at the moment.

**Comment by QuintenJustus** [comment] 2019-07-10 15:41
Closing now because this is likely to be fixed in the next release.

**Closed by QuintenJustus** 2019-07-10 15:41 UTC
